export const SET_GEOLOCATION_SAGA = 'SET_GEOLOCATION_SAGA';
export const SET_CITY = 'SET_CITY';
export const SET_COUNTRY = 'SET_COUNTRY';

export const SET_WEATHER = 'SET_WEATHER';
export const SET_WEATHER_SEARCH = 'SET_WEATHER_SEARCH';
export const SET_WEATHER_CITY = 'SET_WEATHER_CITY';
export const SET_WEATHER_COUNTRY = 'SET_WEATHER_COUNTRY';
export const SET_WEATHER_SEARCH_SAGA = 'SET_WEATHER_SEARCH_SAGA';

export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_IS_LOADING2 = 'SET_IS_LOADING2';
export const SET_ERROR_MESS = 'SET_ERROR_MESS';
export const SET_ERROR_MESS_SEARCH = 'SET_ERROR_MESS_SEARCH';